/* This file was automatically generated by pyNLControl.*/


#include <stdlib.h>
#include <math.h>
#include "qpOASES.hpp"
#include "test1_EVAL_CODE_Call.h"

void test1_Call(double *xGuess, double *a, double *b,  double *xOpt, double *Obj);