/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

int Func(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int Func_alloc_mem(void);
int Func_init_mem(int mem);
void Func_free_mem(int mem);
int Func_checkout(void);
void Func_release(int mem);
void Func_incref(void);
void Func_decref(void);
casadi_int Func_n_out(void);
casadi_int Func_n_in(void);
casadi_real Func_default_in(casadi_int i);
const char* Func_name_in(casadi_int i);
const char* Func_name_out(casadi_int i);
const casadi_int* Func_sparsity_in(casadi_int i);
const casadi_int* Func_sparsity_out(casadi_int i);
int Func_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#ifdef __cplusplus
} /* extern "C" */
#endif
