/* This file was automatically generated by pyNLControl.*/


#include "MHE_Code.h"

void MHE_Code_Call_Func(casadi_real *zGuess, casadi_real *um, casadi_real *ym, casadi_real *zOp, casadi_real *zOut,  casadi_real *p_hat,  casadi_real *x_hat,  casadi_real *Cost );