/* This file was automatically generated by pyNLControl.*/


#include "testKF.h"
#include "testKF_Call.h"

void testKF_Call_Func(casadi_real *u, casadi_real *y, casadi_real *xhatp, casadi_real *Pkp, casadi_real *xhat,  casadi_real *Phat )
{
    int i;

    const casadi_real *arg[4];
    casadi_real *res[2];
    casadi_int iw[0];
    casadi_real w[5];

    
    
    
    
    arg[0] = w + 0;
    
    
    arg[1] = w + 1;
    
    
    arg[2] = w + 2;
    
    
    arg[3] = w + 3;
    
    
    
    
    
    
    res[0] = w + 4;
    
    
    res[1] = w + 5;
    
    
    
    
    
    for (i = 0; i < 1; i++)
        w[i] = u[i-0];
    
    
    for (i = 1; i < 2; i++)
        w[i] = y[i-1];
    
    
    for (i = 2; i < 3; i++)
        w[i] = xhatp[i-2];
    
    
    for (i = 3; i < 4; i++)
        w[i] = Pkp[i-3];
    
    
    KF_func (arg, res, iw, w + 6, 0);
    
    
    
    for (i = 4; i < 5; i++)
        xhat[i-4] = w[i];
    
    
    for (i = 5; i < 6; i++)
        Phat[i-5] = w[i];
    
    
}