/* This file was automatically generated by pyNLControl.*/


#include "testKF.h"

void testKF_Call_Func(casadi_real *u, casadi_real *y, casadi_real *xhatp, casadi_real *Pkp, casadi_real *xhat,  casadi_real *Phat );