/* This file was automatically generated by pyNLControl.*/


#include "MHE_Code.h"
#include "MHE_Code_Call.h"

void MHE_Code_Call_Func(casadi_real *zGuess, casadi_real *um, casadi_real *ym, casadi_real *zOp, casadi_real *zOut,  casadi_real *p_hat,  casadi_real *x_hat,  casadi_real *Cost )
{
    int i;

    const casadi_real *arg[24];
    casadi_real *res[14];
    casadi_int iw[75];
    casadi_real w[1049];

    
    
    
    
    arg[0] = w + 0;
    
    
    arg[1] = w + 14;
    
    
    arg[2] = w + 26;
    
    
    arg[3] = w + 39;
    
    
    
    
    
    
    res[0] = w + 53;
    
    
    res[1] = w + 67;
    
    
    res[2] = w + 68;
    
    
    res[3] = w + 69;
    
    
    
    
    
    for (i = 0; i < 14; i++)
        w[i] = zGuess[i-0];
    
    
    for (i = 14; i < 26; i++)
        w[i] = um[i-14];
    
    
    for (i = 26; i < 39; i++)
        w[i] = ym[i-26];
    
    
    for (i = 39; i < 53; i++)
        w[i] = zOp[i-39];
    
    
    MHE_func (arg, res, iw, w + 70, 0);
    
    
    
    for (i = 53; i < 67; i++)
        zOut[i-53] = w[i];
    
    
    for (i = 67; i < 68; i++)
        p_hat[i-67] = w[i];
    
    
    for (i = 68; i < 69; i++)
        x_hat[i-68] = w[i];
    
    
    for (i = 69; i < 70; i++)
        Cost[i-69] = w[i];
    
    
}