/* This file was automatically generated by pyNLControl.*/


#include "GenCodeTest.h"
#include "GenCodeTest_Call.h"

void GenCodeTest_Call_Func(casadi_real *x, casadi_real *y, casadi_real *z, casadi_real *f1,  casadi_real *f2 )
{
    int i;

    const casadi_real *arg[3];
    casadi_real *res[2];
    casadi_int iw[0];
    casadi_real w[2];

    
    
    
    
    arg[0] = w + 0;
    
    
    arg[1] = w + 1;
    
    
    arg[2] = w + 3;
    
    
    
    
    
    
    res[0] = w + 7;
    
    
    res[1] = w + 8;
    
    
    
    
    
    for (i = 0; i < 1; i++)
        w[i] = x[i-0];
    
    
    for (i = 1; i < 3; i++)
        w[i] = y[i-1];
    
    
    for (i = 3; i < 7; i++)
        w[i] = z[i-3];
    
    
    Func (arg, res, iw, w + 9, 0);
    
    
    
    for (i = 7; i < 8; i++)
        f1[i-7] = w[i];
    
    
    for (i = 8; i < 10; i++)
        f2[i-8] = w[i];
    
    
}