/* This file was automatically generated by pyNLControl.*/


#include <stdio.h>
#include <stdlib.h>
#include <time.h>


#include "GenCodeTest.h"
#include "GenCodeTest_Call.h"

#define BILLION 1000000000.0
#define COL 8

int main(int argc, char const *argv[])
{
    if (argc < 2) {
        printf("Not sufficient input arguments!!!\n");
        printf("Call as: ./EXECUTABLE DATAIN DATAOUT\n");
        return -1;
    }
    int i, j, k, k_prev = 0, IDX_END = 0;

    int ROW = atoi(argv[1]);

    struct timespec start, end;

    FILE *ptr;

    double *DataIn = (double *)malloc(ROW * COL * sizeof(double));

    ptr = fopen(argv[2], "rb");
    fread(DataIn, sizeof(double), ROW * COL, ptr);
    fclose(ptr);

    double t_COMPUTE_TIME = 0.0;

    
    double *x = (double *)malloc(1 * sizeof(double));
    double *y = (double *)malloc(2 * sizeof(double));
    double *z = (double *)malloc(4 * sizeof(double));

    
    double *f1 = (double *)malloc(1 * sizeof(double));
    double *f2 = (double *)malloc(1 * sizeof(double));

    ptr = fopen(argv[3], "w");

    fprintf(ptr, "time,");
    
    for (i=0; i<1; i++)
        fprintf(ptr, "f1_%d,", i+1);
    
    for (i=0; i<1; i++)
        fprintf(ptr, "f2_%d,", i+1);
    

    fprintf(ptr, "Computation_time\n");

    for (k = 0; k < ROW; k++)
    {   
        
        for (i = 0; i < 1; i++)
            x[i] = DataIn[k*COL+0+i+1];
             
        
        for (i = 0; i < 2; i++)
            y[i] = DataIn[k*COL+1+i+1];
             
        
        for (i = 0; i < 4; i++)
            z[i] = DataIn[k*COL+3+i+1];
             
        
    
        clock_gettime(CLOCK_REALTIME, &start);
        GenCodeTest_Call_Func(x, y, z, f1,  f2 );
        clock_gettime(CLOCK_REALTIME, &end);
        t_COMPUTE_TIME = (end.tv_sec - start.tv_sec) + (end.tv_nsec - start.tv_nsec) / BILLION;

        fprintf(ptr, "%f,", DataIn[k*COL]);
        
        
        for (i = 0; i < 1; i++)
            fprintf(ptr, "%f,", f1[i]);
        
        for (i = 0; i < 1; i++)
            fprintf(ptr, "%f,", f2[i]);
        

        fprintf(ptr, "%.10f\n", t_COMPUTE_TIME);

        if ((float)(k - k_prev) / ROW * 100 >= 10) {
            printf("%.0f%% complete!!!\n", (float)k / ROW * 100);
            k_prev = k;
        }
    }

    if ((float)k_prev / ROW * 100 < 100)
    {
        printf("100%% complete!!!\n");
    }

    fclose(ptr);

    return 0;

}