/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) lqr_code_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[5] = {1, 1, 0, 1, 0};

/* lqr_func:(x,ref,Q,R)->(u,K) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3, a4, a5, a6, a7;
  a0=1.;
  a1=9.5122942708333336e-001;
  a2=4.8770572916666664e-002;
  a3=arg[2]? arg[2][0] : 0;
  a4=(a1*a3);
  a4=(a1*a4);
  a5=(a1*a3);
  a5=(a2*a5);
  a6=arg[3]? arg[3][0] : 0;
  a7=(a2*a3);
  a7=(a2*a7);
  a7=(a6+a7);
  a5=(a5/a7);
  a7=(a2*a3);
  a7=(a1*a7);
  a5=(a5*a7);
  a4=(a4-a5);
  a4=(a4+a3);
  a3=(a2*a4);
  a1=(a1*a3);
  a4=(a2*a4);
  a2=(a2*a4);
  a6=(a6+a2);
  a1=(a1/a6);
  a0=(a0+a1);
  a6=arg[1]? arg[1][0] : 0;
  a0=(a0*a6);
  a6=arg[0]? arg[0][0] : 0;
  a6=(a1*a6);
  a0=(a0-a6);
  if (res[0]!=0) res[0][0]=a0;
  if (res[1]!=0) res[1][0]=a1;
  return 0;
}

CASADI_SYMBOL_EXPORT int lqr_func(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int lqr_func_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int lqr_func_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void lqr_func_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int lqr_func_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void lqr_func_release(int mem) {
}

CASADI_SYMBOL_EXPORT void lqr_func_incref(void) {
}

CASADI_SYMBOL_EXPORT void lqr_func_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int lqr_func_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int lqr_func_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real lqr_func_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* lqr_func_name_in(casadi_int i){
  switch (i) {
    case 0: return "x";
    case 1: return "ref";
    case 2: return "Q";
    case 3: return "R";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* lqr_func_name_out(casadi_int i){
  switch (i) {
    case 0: return "u";
    case 1: return "K";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* lqr_func_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s0;
    case 3: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* lqr_func_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int lqr_func_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
