/* This file was automatically generated by pyNLControl.*/


#include "lqr_code.h"
#include "lqr_code_Call.h"

void lqr_code_Call_Func(casadi_real *x, casadi_real *ref, casadi_real *Q, casadi_real *R, casadi_real *u,  casadi_real *K )
{
    int i;

    const casadi_real *arg[4];
    casadi_real *res[2];
    casadi_int iw[0];
    casadi_real w[6];

    
    
    
    
    arg[0] = w + 0;
    
    
    arg[1] = w + 1;
    
    
    arg[2] = w + 2;
    
    
    arg[3] = w + 3;
    
    
    
    
    
    
    res[0] = w + 4;
    
    
    res[1] = w + 5;
    
    
    
    
    
    for (i = 0; i < 1; i++)
        w[i] = x[i-0];
    
    
    for (i = 1; i < 2; i++)
        w[i] = ref[i-1];
    
    
    for (i = 2; i < 3; i++)
        w[i] = Q[i-2];
    
    
    for (i = 3; i < 4; i++)
        w[i] = R[i-3];
    
    
    lqr_func (arg, res, iw, w + 6, 0);
    
    
    
    for (i = 4; i < 5; i++)
        u[i-4] = w[i];
    
    
    for (i = 5; i < 6; i++)
        K[i-5] = w[i];
    
    
}