/* This file was automatically generated by pyNLControl.*/


#include "lqr_code.h"

void lqr_code_Call_Func(casadi_real *x, casadi_real *ref, casadi_real *Q, casadi_real *R, casadi_real *u,  casadi_real *K );